django_homis/urls.py
# urls.py


from django.conf.urls import url, include
from django.contrib import admin


import homis_core.views
import finances.views


ROOT_URL = r"^homis/"


urlpatterns = [
    # Examples:
    # url(r'^$', 'django_homis.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(ROOT_URL + r'$',         finances.views.index),

    url(ROOT_URL + r'finances/', include('finances.urls', namespace = "finances")),
    url(ROOT_URL + r'core/',     include('homis_core.urls', namespace = "homis_core")),

    url(ROOT_URL + r'admin/',    include(admin.site.urls), name = "admin"),
]

finances/urls.py
#finances/url.py


from django.conf.urls import url

from finances import views


urlpatterns = [
    url(r'^$',                  views.index,              name='index'),
    url(r'^add_simple_payment', views.add_simple_payment, name = "add-simple-payment"),
    url(r'^add_transaction',    views.add_transaction,    name = "add-transaction"),

    url(r'^person/(\d+)',       views.person,             name = "person"),
]

homis_core/urls.py
# homis_core/urls.py


from django.conf.urls import url

from homis_core import views


app_name = "homis_core"


urlpatterns = [
    #url(r'^$',     views.index,   name='index'),

    url(r'log_in',  views.log_in,  name = "log-in"),
    url(r'log_out', views.log_out, name = "log-out"),

    url(r'people',  views.people,  name = "people"),
]

homis_core/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(object):
    INFO = "info"
    ERROR = "error"

    @property
    def is_error(self):
        return str(self.level).lower() == self.ERROR

    def __init__(self, text = None, level = None):
        if level is None:
            level = self.INFO

        self.text = text
        self.level = level

    def __str__(self):
        return self.text


class MessageList(object):
    def __init__(self, messages = None):
        self.messages = []
        if messages is not None:
            self.messages.extend(messages)

    def __len__(self):
        return len(self.messages)

    def __iter__(self):
        return iter(self.messages)

    def append(self, msg):
        if isinstance(msg, basestring):
            self.messages.append(Message(msg))
        else:
            self.messages.append(msg)

    def extend(self, messages):
        self.messages.extend(messages)

    def error(self, message):
        self.append(Message(message, Message.ERROR))

    @classmethod
    def make(self, value = None):
        if value is None:
            return MessageList()
        elif isinstance(value, Message):
            return MessageList([value, ])
        elif isinstance(value, MessageList):
            return value
        else:
            return MessageList(value)


class Person(models.Model):
    user  = models.OneToOneField(User, blank = True, null = True, related_name = "person")

    nick_name  = models.CharField(max_length = 128)
    email = models.EmailField(blank = True)

    account_number = models.IntegerField(blank = True, null = True)
    bank_number    = models.IntegerField(blank = True, null = True)

    def __unicode__(self):
        return unicode(self.nick_name)

homis_core/forms.py
from django import forms


class LogInForm(forms.Form):
    username = forms.CharField(min_length = 0, required = False)
    password = forms.CharField(min_length = 0, required = False)

homis_core/views.py
from django.shortcuts import render
from django.contrib.auth import logout, login, authenticate

from homis_core.forms import LogInForm
from homis_core.models import Person, MessageList


def index(request, messages = None):
    messages = MessageList.make(messages)

    return render(
        request,
        'homis_core/base.html',
        {
            "messages": messages,
        }
    )


def log_in(request):
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                username = data["username"],
                password = data["password"])
            if user is None:
                messages = ["Incorrect username or password.", ]
            else:
                login(request, user)
                messages = ["Logged in as " + data["username"] + ".", ]
        else:
            messages = ["Log in form invalid.", ]
    else:
        return index(request)
    return index(request, messages)


def log_out(request):
    logout(request)
    messages = ["User logged out."]
    return index(request, messages)


def people(request):
    return render(
        request,
        "homis_core/person_list.html",
        {
            'person_list': Person.objects.all(),
        }
    )

homis_core/templates/homis_core/base.html
{% load staticfiles %}
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static "homis_core/base.css" %}" />
		<link rel="stylesheet" type="text/css" href="{% static "finances/finances.css" %}" />

		<script type="text/javascript" src="{% static "homis_core/jquery-1.11.2.min.js" %}"></script>

		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

		{% block meta %}
		{% endblock %}
	</head>

	<body>
		<div class="title_bar">
			<div class="login_box">
				{% if user.is_authenticated %}
					{{ user.username }} | <a href="{% url 'homis_core:log-out' %}">log out</a>
				{% else %}
					<form action="{% url 'homis_core:log-in' %}" method="POST">
						{% csrf_token %}
						username:
						<input type="text" name="username" />
						password:
						<input type="password" name="password" />
						<input type="submit" value="log in" />
					</form>
				{% endif %}	
			</div>

			{% block title %}
			<h1>Core</h1>
			{% endblock %}

			{% block tile_menu %}
			<ul>
				<li><a href="{% url 'homis_core:people' %}">People</a></li>
				<li><a href="{% url 'finances:index' %}">Finances</a></li>
				<li><a href="{% url 'admin:index' %}">Admin</a></li>
			</ul>
			{% endblock %}
		</div>

		<div class="action_bar">
			<a href="{% url 'finances:add-simple-payment' %}" class="action_button">Simple payment</a>
			<a href="{% url 'finances:add-transaction' %}" class="action_button">Transaction</a>
		</div>

		<span class="content">
			{% if messages %}
			<div class="message_container">
				{% for message in messages %}
				<div class="message_box {% if message.is_error %}message_error{% endif %}">
					{{ message }}
				</div>
				{% endfor %}
			</div>
			{% else %}
			<!-- Messages: {{ messages }} -->
			{% endif %}

			{% block content %}
			{% endblock %}
		</span>
	</body>
</html>

homis_core/templates/homis_core/person_list.html
{% extends "homis_core/base.html" %}

{% block content %}
<table>
	<tr>
		<th>Nick</th>
		<th>User Name</th>
		<th>E-mail</th>
		<th>Bank Account</th>
	</tr>
	{% for person in person_list %}
	<tr class="{% cycle "odd_row" "even_row" %}">
		<td>{{ person.nick_name }}</td>
		<td>{% if person.user %}{{ person.user }}{% endif %}</td>
		<td><a href="mailto:{{ person.email }}">{{ person.email }}</a></td>
		<td>
			{% if person.account_number %}
				{{ person.account_number }} / {{ person.bank_number }}
			{% endif %}
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}